name: Stage Placeholder

on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Echo stage info
        run: echo "Stage branch detected. Placeholder for future web UI tests."
