name: Promote Test to Stage

on:
  workflow_run:
    workflows: ["Integration test for ASG and ALB"] 
    types:
      - completed

permissions:
  contents: write

jobs:
  promote:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"

      - name: Promote test to stage
        run: |
          git checkout test
          git pull origin test
          git checkout -B stage
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} stage --force
