name: Deploy to Staging

on:
  push:
    branches: [stage]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: environments/stage
        run: terraform init -reconfigure

      - name: Terraform Apply
        working-directory: environments/stage
        run: terraform apply -auto-approve
