name: Terratest for VPC Module

on:
  push:
    paths:
      - 'modules/vpc/**'
      - 'tests/modulesvpc/**'
  pull_request:
    paths:
      - 'modules/vpc/**'
      - 'tests/modules/vpc/**'

jobs:
  terratest:
    name: Terratest (VPC Module)
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Go dependencies
        working-directory: tests/modules/vpc
        run: |
          go mod init vpc_test || true
          go get github.com/gruntwork-io/terratest/modules/terraform
          go get github.com/stretchr/testify/assert

      - name: Run Terratest
        working-directory: tests/modules/vpc
        run: go test -v
